### ISSUE TITLE
Error while flashing an example

### ISSUE THREAD

**Issue by FlaviusRabuga** [UPB-CS-OpenSourceUpstream/libtock-rs#6]
Hey, I cloned the repo and followed the steps from the main README, but when I run the 
make flash-microbit_v2 EXAMPLE=console   command,
I get this error: https://imgur.com/a/s46jsJn
I am currently using WSL

**Comment by alexandruradovici** [comment]
There are several issue here:

1. You do need [tockloader](https://github.com/tock/tockloader) version 1.10.0-dev installed, that means installing it from GitHub and not using pip (which installs and older version)
2. You will need a real Linux to flash the board, as WSL does not seem to be able to redirect USB ports. You can use VirtualBox or VMWare, both know how to forwards USB ports.
